baseURL = "https://swiftscripters.github.io/"
languageCode = "en-us"
title = "SwiftScripters"

[params]
  tagline = "Code That's Swift, Solutions That Stick."
  github  = "https://github.com/SwiftScripters"
  sponsor = "https://github.com/sponsors/SwiftScripters"

[menu]
  [[menu.main]]
    name   = "Home"
    url    = "/"
    weight = 1
  [[menu.main]]
    name   = "Projects"
    url    = "/projects/"
    weight = 2
